### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by luoan2** [ZJUTDevelopers/standardmotion#1]
请问一下作者，我按照您的说明运行后，点击检测出现openpose后界面就卡住，无法比对，请问一下您该如何解决

**Comment by gorgeousdays** [comment]
> 请问一下作者，我按照您的说明运行后，点击检测出现openpose后界面就卡住，无法比对，请问一下您该如何解决

你好 单独运行openpose是否存在问题，界面卡住后是否存在报错，可以详细描述一下情况吗？

**Comment by luoan2** [comment]
> > 请问一下作者，我按照您的说明运行后，点击检测出现openpose后界面就卡住，无法比对，请问一下您该如何解决
> 
> 你好 单独运行openpose是否存在问题，界面卡住后是否存在报错，可以详细描述一下情况吗？

openpose单独运行不存在问题，只要点击开始检测或输入文件，openpose正常运行，但是gui界面就会无响应，只能强制关闭

**Comment by gorgeousdays** [comment]
关于你给出的信息，难以判断是什么问题，应该是环境配置出了错。已上传了Release版本，如果仍然不行，那我也帮不上忙了。

**Comment by luoan2** [comment]
[您有其他联系方式吗，可以直接发图片给您吗

**Comment by gorgeousdays** [comment]
不好意思，我所能提供的帮助到此为止了。
